In [1]:
import scipy.stats as st
print st.norm.ppf(.975)

1.95996398454


In [2]:
print st.norm.ppf(.9985)

2.96773792534


In [3]:
import numpy as np
import pandas as pd

import scipy
from statsmodels.stats.weightstats import *
from statsmodels.stats.proportion import proportion_confint

In [4]:
def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)

In [16]:
p1 = 104./11037
p2 = 189./11034
print p2-p1

0.007706023976


In [17]:
z = scipy.stats.norm.ppf(1 - 0.05 / 2.)   
p2 = 104./11037
p1 = 189./11034
    
left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ 11037 + p2 * (1 - p2)/ 11034)
right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ 11037 + p2 * (1 - p2)/ 11034)
print (left_boundary, right_boundary)

(0.0046878682721335392, 0.010724179679876024)


In [9]:
sh1 = p1 / (1-p1)
sh2 = p2 / (1-p2)
print sh2 / sh1

1.83205394191


In [10]:
x1 = np.zeros(11037)
for i in range(104):
    x1[i] = 1
    
x2 = np.zeros(11034)
for i in range(189):
    x2[i] = 1


In [11]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples

In [12]:
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

In [13]:
def odds2(b): 
    pb = np.sum(b) / len(b)
    return pb / (1-pb)

In [15]:
np.random.seed(0)

x1_scores = map(lambda x: odds2(x), get_bootstrap_samples(x1, 1000))
x2_scores = map(lambda x: odds2(x), get_bootstrap_samples(x2, 1000))

odds_score = np.zeros(1000)
for i in range(1000):
    odds_score[i] = x2_scores[i] / x1_scores[i]

print "95% CI for odds",  stat_intervals(odds_score, 0.05)

95% CI for odds [ 1.44419465  2.34321168]


# Задание 2

In [18]:
stats.binom_test(67, 100, .75, alternative = 'two-sided')

0.082222588913866079

In [19]:
data = pd.read_csv('pines.txt', sep = '\t', header=0)
data.head(5)

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [20]:
data.shape

(584, 2)

In [32]:
bin_x = [0.0, 40., 80., 120., 160., 200.]
ret = stats.binned_statistic_2d(data.sn, data.we, None, 'count', bins=[bin_x,bin_x])
#print ret.binnumber.mean()
print ret.statistic.mean()

23.36


In [33]:
print ret.statistic

[[ 18.  26.  29.  25.  20.]
 [ 14.  12.  22.  34.  25.]
 [ 12.  24.  15.  50.  37.]
 [  8.  19.  31.  50.   7.]
 [  7.   8.  37.  27.  27.]]


In [34]:
arr_stat = np.reshape(ret.statistic, 25)
print arr_stat

[ 18.  26.  29.  25.  20.  14.  12.  22.  34.  25.  12.  24.  15.  50.  37.
   8.  19.  31.  50.   7.   7.   8.  37.  27.  27.]


In [35]:
from scipy.stats import chisquare
chisquare(arr_stat)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.5746697749672791e-20)